name: Release

on:
  push:
  pull_request:

jobs:
  build-release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install build package
        run: |
          pip install --upgrade pip
          pip install build
          pip freeze

      - name: Build release
        run: |
          python -m build --sdist --wheel .
          ls -l dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.9
        if: startsWith(github.ref, 'refs/tags/')
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
          
